use_frameworks!

platform :ios, '8.0'

target 'KKCategoryListView_Example' do
  pod 'KKCategoryListView', :path => '../'

  target 'KKCategoryListView_Tests' do
    inherit! :search_paths

    
  end
end
